services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${FRONT_CONTAINER_NAME:-produtividade-frontend}
    restart: unless-stopped
    # sem ports: NPM acessa via rede docker compartilhada
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  proxy:
    external: true
    name: ${NPM_DOCKER_NETWORK:-npm_network}
